### ISSUE TITLE
Download expired

### ISSUE THREAD

**Issue by Calitar** [YoRyan/openrails-timetables#1]
It seems the timetables are no longer available because the latest artifact download has expired. If possible could you please upload the timetables somewhere more permanent (or at least make it available here again)? It would be much appreciated.

**Comment by YoRyan** [comment]
Fixed the build and made the artifacts again; thanks for the report! That's just what I get for trying to automate away the work of making new releases.

Since I don't expect to make any change to these timetables for the foreseeable future, I'll also publish them to my website.
